package com.bang_ggood.global.exception;

public enum BangggoodCode {

    ARTICLE_NOT_FOUND,
    AUTH_ACCESS_TOKEN_EMPTY,
    AUTH_TOKEN_EMPTY,
    AUTH_TOKEN_INVALID,
    AUTH_TOKEN_NOT_OWNED_BY_USER,
    AUTH_TOKEN_USER_MISMATCH,
    CHECKLIST_ERROR,
    CHECKLIST_NOT_FOUND,
    CHECKLIST_SERVER_ERROR,
    CUSTOM_ERROR,
    GUEST_USER_NOT_FOUND,
    GUEST_USER_UNEXPECTED_EXIST,
    INTERNAL_SERVER_ERROR,
    LIKE_ALREADY_EXISTS,
    LIKE_NOT_EXISTS,
    OAUTH_SERVER_ERROR,
    PASSWORD_HASHING_ERROR,
    QUESTION_ERROR,
    STATION_SERVER_ERROR,
    UNAUTH_ERROR,
    USER_EMAIL_ALREADY_USED,
    USER_INVALID_FORMAT,
    USER_NOT_FOUND,
}
