CREATE TABLE if not exists users
(
    id  bigint  generated by default as identity,
    name varchar(255) not null,
    created_at TIMESTAMP not null,
    modified_at TIMESTAMP not null,
    primary key (id)
);

CREATE TABLE if not exists category_priority
(
    id  bigint  generated by default as identity,
    category_id tinyint not null,
    user_id bigint not null,
    created_at TIMESTAMP not null,
    modified_at TIMESTAMP not null,
    primary key (id),
    foreign key (user_id) references users
);


CREATE TABLE test_entity
(
    id bigint  generated by default as identity,
    name varchar(255) not null,
    created_at TIMESTAMP not null,
    modified_at TIMESTAMP not null,
    primary key (id)
);

